### PR TITLE
* Removed bash command

### PR DESCRIPTION
**Pull request by d4nj1**

### CODE REVIEW

**Comment by d4nj1** [comment]
Bad change. Will try to fix an create working PR.

**Comment by MartinX3** [comment]
But thank you for your help

Since it has a shebang, you could add a `./` as prefix of the filename and look if it still works

**Comment by d4nj1** [comment]
I get the following error when reaching this line:

**bash: SKIP_SYNC=TRUE: No such file or directory**

If I change to either:

```SKIP_SYNC=TRUE bash -c "$1/repo_update.sh"```

or

```
export SKIP_SYNC=TRUE
bash $1/repo_update.sh
```

it works again.

**Comment by MartinX3** [comment]
Oh shit, yes
You're right
I didn't test the late made change

**Pull request closed without merging**
